import React from "react";
import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";

import clsx from "clsx";

import { Footer } from "./layout/components/Footer";
import { NavBar } from "./layout/components/NavBar";

import "./app.css";

const firaCode = Fira_Code({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <head>
        <meta content="width=device-width, initial-scale=1.0" name="viewport" />
      </head>
      <body className={clsx(firaCode.className, "min-w-[360px] bg-[#010C15]")}>
        <div className="flex h-svh flex-col p-10">
          <div className="bg-deep-navy border-line flex h-full flex-col overflow-hidden rounded-lg border">
            <NavBar />
            <main className="grow overflow-hidden">{children}</main>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
};
export default RootLayout;
