import "@/styles/globals.css";

import React from "react";
import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";

import clsx from "clsx";

import { GlobalLayout } from "@/components/GlobalLayout";

import * as styles from "./layout.css";

const firaCode = Fira_Code({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={clsx(firaCode.className, styles.rootContainer)}>
        <GlobalLayout>{children}</GlobalLayout>
      </body>
    </html>
  );
};
export default RootLayout;
